### ISSUE TITLE
No code in this repo

### ISSUE THREAD

**Issue by hansenms** [Azure-Samples/python-docs-hello-world#1]
Was there not supposed to some Python sample code in this repo?

The [tutorial](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-python) seems to indicate so.

**Comment by davoodharun** [comment]
+1

**Comment by 5nowx** [comment]
+1

**Comment by buckle2000** [comment]
+1

**Comment by SyntaxC4** [comment]
Sorry for the delay on this sample. We will be updating the article in the coming days as well. This article was shipped slightly ahead of planned.
