### ISSUE TITLE
Files missing?

### ISSUE THREAD

**Issue by platipusica** [Azure-Samples/python-docs-hello-world#11]
Hi there!

Many thanks for this tutorial!

I have a question though, in file web.2.7.config, line 6
D:\home\site\wwwroot\env\Scripts\activate_this.py

and also web.3.4.config:
D:\home\site\wwwroot\env\Scripts\python.exe

Can you confirm how to get this files in env/Scripts folder? From where do we get activate_this.py file?

Thanks!

**Comment by kraigb** [comment]
Closing old issues.
