### ISSUE TITLE
Python Flask app on Azure Web App for Containers has no deployment instructions

### ISSUE THREAD

**Issue by gbowerman** [Azure-Samples/python-docs-hello-world#23]
See: [Python Flask app on Azure Web App for Containers](https://github.com/Azure-Samples/python-docs-hello-world) - there is a stub flask app, and no information about Azure Web App for Containers at all. No-one could figure out how to deploy a web app for containers from this sample.

Please add some deployment instructions for containers.

**Comment by gbowerman** [comment]
@asavaritayal FYI

**Comment by kraigb** [comment]
Deploying containers is beyond the scope of this specific example. However, see https://github.com/Microsoft/python-sample-vscode-flask-tutorial along with the associated tutorial, https://code.visualstudio.com/docs/python/tutorial-deploy-containers.
