### ISSUE TITLE
Use python3 in devops pipeline example

### ISSUE THREAD

**Issue by 9034725985** [Azure-Samples/python-docs-hello-world#25]
I am currently working on https://github.com/kusl/openroomazurewebsites 

If you look at the first commit at https://github.com/kusl/openroomazurewebsites/commit/c673623bf7c33fdfa197e36e407771e16609a96f , you will see the project used to use Python 2. 
Python 2 will EOL on January 01, 2020. https://pythonclock.org/  

I have made some changes in the above project to use Python3. 
For instance, we don't use Ubuntu anymore. 
We use python:stretch (Debian) which automatically gives us the latest Python3. 

I think if we devops pipeline to python 3, it will help the azure developer community (especially the students who are trying to learn devops and tomorrow's IT manpower) a lot. Thanks!

**Comment by wangyuliangabc** [comment]
---
1
-1
2
-2
-3-4-5

**Comment by kraigb** [comment]
Closing as issue is beyond the scope of this example.
