### ISSUE TITLE
Adding another route causes 404 on cloud deploy only

### ISSUE THREAD

**Issue by kevinskrei** [Azure-Samples/python-docs-hello-world#4]
Originally, In main.py there is a function named `hello_world`
```
@app.route('/')
def hello_world():
    return 'Hello, World!'
```

I added another function below
```
@app.route('/hello')
def hello_path():
    return "HELLO FROM PATH"
```
So the full script is as follows:

```    
from flask import Flask
app = Flask(__name__)
app.debug = True
    
@app.route('/')
def hello_world():
    return 'Hello, World!'
    
@app.route('/hello')
def hello_path():
    return "HELLO FROM PATH"
    
if __name__ == '__main__':
    app.run()
```

When I run this on my localhost both endpoints work correctly and return their respective strings. However, after deploying via git to my azure website, I can only get the response from `xxx.azurewebsites.net/` to work correctly (returns "Hello, World!"). When I try and hit `xxx.azurewebsites.net/hello` I get a 404 error. 

I'm not sure why it only works with the default route in the cloud when everything works fine locally. Is this a setup issue? Is there anyway I can debug the routing issues on Azure?

**Comment by robbiesmith** [comment]
I'm having the same problem. I'd love to know how to fix it - seems like it should be straightforward.

**Comment by robbiesmith** [comment]
not a solution to this problem - but I was able to workaround it by using the Azure SDK in visual studio and publishing to the web app from there.

**Comment by hgirish** [comment]
Adding System.Web and System.WebServer block to web.3.4.config from https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/app-service-web/web-sites-python-configure.md worked for me

**Comment by jtmott** [comment]
@hgirish solution worked for me as well, i.e., add the following to your web.3.4.config:
```
<system.web>
    <compilation debug="true" targetFramework="4.0" />
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <handlers>
      <remove name="Python27_via_FastCGI" />
      <remove name="Python34_via_FastCGI" />
      <add name="Python FastCGI"
           path="handler.fcgi"
           verb="*"
           modules="FastCgiModule"
           scriptProcessor="D:\Python34\python.exe|D:\Python34\Scripts\wfastcgi.py"
           resourceType="Unspecified"
           requireAccess="Script" />
    </handlers>
    <rewrite>
      <rules>
        <rule name="Static Files" stopProcessing="true">
          <conditions>
            <add input="true" pattern="false" />
          </conditions>
        </rule>
        <rule name="Configure Python" stopProcessing="true">
          <match url="(.*)" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_URI}" pattern="^/static/.*" ignoreCase="true" negate="true" />
          </conditions>
          <action type="Rewrite" url="handler.fcgi/{R:1}" appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
```

**Comment by kraigb** [comment]
Closing as an obsolete issue.
