### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by thigm85** [Azure-Samples/python-docs-hello-world#6]
Hi,

I have followed the [tutorial](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-python) and the deployment were successful. However I am getting `HTTP Error 500.0 - Internal Server Error`.

That is what appear in the logs:

IIS received the request; however, an internal error occurred during the processing of the request. 

IIS was not able to access the web.config file for the Web site or application. 
This can occur:
* if the NTFS permissions are set incorrectly.
* IIS was not able to process configuration for the Web site or application.
* The authenticated user does not have permission to use this DLL.
* The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.

Did I miss some step on the tutorial?

**Comment by tobybrad** [comment]
Looks like this was *just* fixed. Pull the latest version of this repo and try again.

**Comment by thigm85** [comment]
Yes, the latest commit fixed it. Thanks.
