### ISSUE TITLE
Dash app by plotly

### ISSUE THREAD

**Issue by sushi-maximus** [Azure-Samples/python-docs-hello-world#7]
Can you create a sample dash app for azure?

**Comment by AustenLamacraft** [comment]
+1 I can't deploy the sample app from the [Dash documentation](https://dash.plot.ly/deployment) on Azure, even though a Flask app deploys without problems.

**Comment by kraigb** [comment]
Closing as not relevant to this specific sample.

**Comment by hasmm** [comment]
At least put a comment for them on how to address this issue. Microsoft Engineers are the worst!
