### ISSUE TITLE
App crashes when trying to create MongoDB client

### ISSUE THREAD

**Issue by suleymanov** [Azure-Samples/python-docs-hello-world#8]
I added pymongo==3.5.1 to reqs and initiated client, which now causes my web app to crash (results in error 500.0 when trying to access). What might be the issue?

Code for deployment can be viewed in my fork:

https://github.com/suleymanov/python-docs-hello-world

**Comment by kraigb** [comment]
Closing old issues; this is a won't fix because it's beyond the scope of this simple sample. It'd be better to follow up with Flask directly on such matters.
